name: PUSH_IMAGE_TO_DOCKERHUB
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Docker Image Push
        run: |
          docker build -t app .
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin 
          docker tag app abhishek3459/threads_backend_app
          docker push abhishek3459/threads_backend_app
          
